// apps/playground/src/vue/LinkedDemo.vue
<script setup lang="ts">
import { PasswordStrengthMeter } from '@passcore/vue'
import { ref } from 'vue'
import { meterTexts, t } from '../lib/i18n'
import PasswordField from './PasswordField.vue'

const username = ref('')
const password = ref('')
const texts = meterTexts()
</script>

<template>
  <div class="field">
    <label class="field__label" for="vue-username">{{ t('field.username') }}</label>
    <input
      id="vue-username"
      v-model="username"
      class="input"
      type="text"
      autocomplete="username"
      autocapitalize="off"
      spellcheck="false"
      :placeholder="t('field.usernamePlaceholder')"
    >
  </div>
  <PasswordField id="vue-linked" v-model="password" described-by="vue-linked-strength">
    <PasswordStrengthMeter id="vue-linked-strength" :password="password" :user-inputs="[username]" show-percent v-bind="texts" />
  </PasswordField>
</template>

// apps/playground/src/svelte/LinkedDemo.svelte
<script lang="ts">
  import { PasswordStrengthMeter } from '@passcore/svelte'
  import { meterTexts, t } from '../lib/i18n'
  import PasswordField from './PasswordField.svelte'

  let username = $state('')
  let password = $state('')
</script>

<div class="field">
  <label class="field__label" for="svelte-username">{t('field.username')}</label>
  <input
    id="svelte-username"
    class="input"
    type="text"
    autocomplete="username"
    autocapitalize="off"
    spellcheck="false"
    placeholder={t('field.usernamePlaceholder')}
    bind:value={username}
  />
</div>
<PasswordField id="svelte-linked" bind:value={password} describedBy="svelte-linked-strength">
  <PasswordStrengthMeter id="svelte-linked-strength" {password} userInputs={[username]} showPercent {...meterTexts()} />
</PasswordField>
