// apps/playground/src/vue/PasswordInput.vue
<script setup lang="ts">
import { computed, nextTick, ref } from 'vue'
import { keepFocus, revealLabel } from '../lib/reveal'
import Icon from './Icon.vue'

/** A password input with the playground's show/hide button inside it (see src/lib/reveal.ts). */
defineProps<{ id: string, describedBy?: string }>()
const model = defineModel<string>({ required: true })

const shown = ref(false)
const input = ref<HTMLInputElement | null>(null)
const label = computed(() => revealLabel(shown.value))

async function toggle(): Promise<void> {
  const element = input.value
  const selection = element && element.selectionStart !== null && element.selectionEnd !== null
    ? [element.selectionStart, element.selectionEnd] as const
    : null
  shown.value = !shown.value
  // changing the type can move the caret: put it back where it was
  await nextTick()
  if (element && selection && document.activeElement === element) {
    element.setSelectionRange(selection[0], selection[1])
  }
}
</script>

<template>
  <div class="pw">
    <input
      :id="id"
      ref="input"
      v-model="model"
      class="input pw__input"
      :type="shown ? 'text' : 'password'"
      autocomplete="new-password"
      autocapitalize="off"
      spellcheck="false"
      :aria-describedby="describedBy"
    >
    <button
      type="button"
      class="reveal"
      :aria-controls="id"
      :aria-pressed="String(shown)"
      :aria-label="label"
      @mousedown="keepFocus"
      @click="toggle"
    >
      <Icon name="eye" class-name="icon reveal__show" />
      <Icon name="eyeOff" class-name="icon reveal__hide" />
    </button>
  </div>
</template>

// apps/playground/src/svelte/PasswordInput.svelte
<script lang="ts">
  import { tick } from 'svelte'
  import { keepFocus, revealLabel } from '../lib/reveal'
  import Icon from './Icon.svelte'

  /** A password input with the playground's show/hide button inside it (see src/lib/reveal.ts). */
  let { id, value = $bindable(''), describedBy }: { id: string, value?: string, describedBy?: string } = $props()

  let shown = $state(false)
  let input: HTMLInputElement | undefined = $state()
  const label = $derived(revealLabel(shown))

  async function toggle(): Promise<void> {
    const selection = input && input.selectionStart !== null && input.selectionEnd !== null
      ? [input.selectionStart, input.selectionEnd] as const
      : null
    shown = !shown
    // changing the type can move the caret: put it back where it was
    await tick()
    if (input && selection && document.activeElement === input) {
      input.setSelectionRange(selection[0], selection[1])
    }
  }
</script>

<div class="pw">
  <input
    bind:this={input}
    bind:value
    class="input pw__input"
    {id}
    type={shown ? 'text' : 'password'}
    autocomplete="new-password"
    autocapitalize="off"
    spellcheck="false"
    aria-describedby={describedBy}
  />
  <button
    type="button"
    class="reveal"
    aria-controls={id}
    aria-pressed={shown}
    aria-label={label}
    onmousedown={keepFocus}
    onclick={toggle}
  >
    <Icon name="eye" className="icon reveal__show" />
    <Icon name="eyeOff" className="icon reveal__hide" />
  </button>
</div>
