// apps/playground/src/svelte/EventsDemo.svelte
<script lang="ts">
  import { PasswordStrengthMeter } from '@passcore/svelte'

  let password = $state('')
  let percent = $state(0)
  let status = $state('')

  const submit = (event: SubmitEvent) => {
    event.preventDefault()
    status = 'Submitted in the playground: nothing was sent.'
  }
</script>

<form onsubmit={submit}>
  <div class="field">
    <label for="svelte-events">Password</label>
    <input id="svelte-events" type="password" autocomplete="new-password" aria-describedby="svelte-events-strength" bind:value={password} />
    <PasswordStrengthMeter id="svelte-events-strength" {password} onscore={(value) => (percent = value)} />
  </div>
  <p class="hint">Score: <output for="svelte-events">{percent}%</output></p>
  <div class="actions">
    <button type="submit" class="btn btn--primary" disabled={percent <= 75}>Send</button>
    <p class="hint" role="status">{status}</p>
  </div>
</form>

// apps/playground/src/vue/EventsDemo.vue
<script setup lang="ts">
import { PasswordStrengthMeter } from '@passcore/vue'
import { ref } from 'vue'

const password = ref('')
const percent = ref(0)
const status = ref('')

const onScore = (value: number): void => {
  percent.value = value
}

const submit = (): void => {
  status.value = 'Submitted in the playground: nothing was sent.'
}
</script>

<template>
  <form @submit.prevent="submit">
    <div class="field">
      <label for="vue-events">Password</label>
      <input id="vue-events" v-model="password" type="password" autocomplete="new-password" aria-describedby="vue-events-strength">
      <PasswordStrengthMeter id="vue-events-strength" :password="password" @score="onScore" />
    </div>
    <p class="hint">Score: <output for="vue-events">{{ percent }}%</output></p>
    <div class="actions">
      <button type="submit" class="btn btn--primary" :disabled="percent <= 75">Send</button>
      <p class="hint" role="status">{{ status }}</p>
    </div>
  </form>
</template>
