// apps/playground/src/svelte/TranslationsDemo.svelte
<script lang="ts">
  import { PasswordStrengthMeter } from '@passcore/svelte'
  import ca from '@passcore/svelte/locales/ca.json'
  import en from '@passcore/svelte/locales/en.json'
  import es from '@passcore/svelte/locales/es.json'
  import { t } from '../lib/i18n'
  import { currentLang } from '../lib/lang'
  import PasswordField from './PasswordField.svelte'

  const bundled = { en, es, ca }
  let password = $state('')
</script>

<PasswordField id="svelte-translations" bind:value={password} describedBy="svelte-translations-strength">
  <PasswordStrengthMeter
    id="svelte-translations-strength"
    {password}
    translations={bundled[currentLang()]}
    locale={currentLang()}
    label={t('meter.label')}
    showPercent
  />
</PasswordField>

// apps/playground/src/vue/TranslationsDemo.vue
<script setup lang="ts">
import { PasswordStrengthMeter } from '@passcore/vue'
import ca from '@passcore/vue/locales/ca.json'
import en from '@passcore/vue/locales/en.json'
import es from '@passcore/vue/locales/es.json'
import { ref } from 'vue'
import { t } from '../lib/i18n'
import { currentLang } from '../lib/lang'
import PasswordField from './PasswordField.vue'

const bundled = { en, es, ca }
const password = ref('')
const lang = currentLang()
</script>

<template>
  <PasswordField id="vue-translations" v-model="password" described-by="vue-translations-strength">
    <PasswordStrengthMeter
      id="vue-translations-strength"
      :password="password"
      :translations="bundled[lang]"
      :locale="lang"
      :label="t('meter.label')"
      show-percent
    />
  </PasswordField>
</template>
