// packages/react/src/password-strength-meter.tsx
import type { Result } from '@passcore/core'
import { useEffect, useMemo, useRef, type ReactElement } from 'react'
import { useStrengthResult, useTranslatedStrength, type PasswordOptions } from './use-password-strength'

export interface PasswordStrengthMeterProps extends PasswordOptions {
  password: string
  /** id of the text element, for aria-describedby on the input. */
  id?: string
  /** Added to the wrapper. */
  className?: string
  /** Called with the percent and the core result when the evaluated result changes (not on mount). */
  onScore?: (percent: number, result: Result) => void
  /** Called with the translated text when the message changes (not on mount). */
  onText?: (text: string, result: Result) => void
}

/**
 * A password strength meter with the standard markup: a meter with a bar,
 * an optional percentage and the message, linked to the input with `id`.
 */
export function PasswordStrengthMeter(props: PasswordStrengthMeterProps): ReactElement {
  const { password, id, className, onScore, onText, ...options } = props
  const result = useStrengthResult(password, options)
  const strength = useTranslatedStrength(result, options)
  const { showPercent = false, showText = true, label = 'Password strength' } = options

  // the latest callbacks and text, read by the effects below (updated after each commit)
  const latest = useRef({ onScore, onText, text: strength.text })
  useEffect(() => {
    latest.current = { onScore, onText, text: strength.text }
  })

  // by value: a new but equal result (e.g. the same options passed again) doesn't fire onScore
  const resultKey = useMemo(() => JSON.stringify(result), [result])
  const previousKey = useRef<string | undefined>(undefined)
  useEffect(() => {
    const previous = previousKey.current
    previousKey.current = resultKey
    // the first run is the mount, and StrictMode's re-run sees the same result
    if (previous === undefined || previous === resultKey) {
      return
    }
    latest.current.onScore?.(result.percent, result)
  }, [resultKey, result])

  const messageKey = JSON.stringify([result.message.key, result.message.params])
  const previousMessage = useRef<string | undefined>(undefined)
  useEffect(() => {
    const previous = previousMessage.current
    previousMessage.current = messageKey
    if (previous === undefined || previous === messageKey) {
      return
    }
    latest.current.onText?.(latest.current.text, result)
  }, [messageKey, result])

  const wrapperClass = [
    'pass-wrapper',
    `pass-level-${result.level}`,
    result.valid ? '' : 'pass-invalid',
    className ?? '',
  ].filter(Boolean).join(' ')

  return (
    <div className={wrapperClass}>
      <div
        className="pass-meter"
        role="meter"
        aria-label={label}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuenow={result.percent}
        aria-valuetext={strength.levelText}
      >
        <div className="pass-bar" style={{ width: `${result.percent}%` }} />
      </div>
      {showPercent && (
        <span className="pass-percent">{`${result.percent}%`}</span>
      )}
      {showText && <span className="pass-text" id={id} aria-live="polite">{strength.text}</span>}
    </div>
  )
}

// packages/svelte/src/lib/PasswordStrengthMeter.svelte
<script lang="ts">
  import { untrack } from 'svelte'
  import { passwordStrength, type PasswordStrengthMeterProps } from './strength.svelte.js'

  const props: PasswordStrengthMeterProps = $props()

  const strength = passwordStrength(() => props.password, () => props)

  const showPercent = $derived(props.showPercent ?? false)
  const showText = $derived(props.showText ?? true)
  const label = $derived(props.label ?? 'Password strength')
  const wrapperClass = $derived([
    'pass-wrapper',
    `pass-level-${strength.result.level}`,
    strength.result.valid ? '' : 'pass-invalid',
    props.class,
  ].filter(Boolean).join(' '))

  // callbacks fire on changes after mount only (the first run just records the result), and
  // only when the evaluated result changes by value: re-renders with the same password don't fire
  let previous: { result: string, message: string } | undefined
  $effect(() => {
    const result = strength.result
    const json = JSON.stringify(result)
    const message = JSON.stringify(result.message)
    const before = previous
    previous = { result: json, message }
    if (before !== undefined && json !== before.result) {
      untrack(() => {
        props.onscore?.(result.percent, result)
        if (message !== before.message) {
          props.ontext?.(strength.text, result)
        }
      })
    }
  })
</script>

<div class={wrapperClass}>
  <div
    class="pass-meter"
    role="meter"
    aria-label={label}
    aria-valuemin={0}
    aria-valuemax={100}
    aria-valuenow={strength.result.percent}
    aria-valuetext={strength.levelText}
  >
    <div class="pass-bar" style:width="{strength.result.percent}%"></div>
  </div>
  {#if showPercent}
    <span class="pass-percent">{strength.result.percent}%</span>
  {/if}
  {#if showText}
    <span class="pass-text" id={props.id} aria-live="polite">{strength.text}</span>
  {/if}
</div>
